name: 'ga4'
version: '6.1.0'
config-version: 2
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  ga4:
    staging:
      +schema: mother_ny_pbc_ga4_stg_dev
      +materialized: table
    marts:
      +schema: mother_ny_pbc_ga4_mart_dev
      +materialized: table
